"""
This Snakemake workflow runs cellmates on pre-simulated data from CNAsim,
evaluates the results, and combines them into a summary statistics file.
The dataset directory structure is assumed to be the one from the DICE experiments,
therefore
datasets/
    A1_0/
        0/
            anndata.h5ad
            cm_out/
                distance_matrix.npy
                tree.nwk
                cell_names.txt
        1/
            ...
    A1_1/
        ...
    evaluation/
        stats.csv
The final results are combined into a single CSV file with evaluation statistics.
"""
configfile: "config/config.yaml"

import os
import glob
# which datasets to process is defined in the config file
wildcard_constraints:
    dataset="|".join(config["datasets"]),
    seed="\d+" if len(config["seeds"]) == 0 else "|".join(str(s) for s in config["seeds"]),
    datatype="|".join(["", "_cn"])

# parameters
data_dir = config["data_dir"]
datatypes = config["datatypes"]
eval_dir = os.path.join(data_dir, "evaluation")
# constraint
DATASET_LIST = glob_wildcards(data_dir + "/{dataset}/{seed}")

allowed_datasets = set(config["datasets"])
allowed_seeds = {str(s) for s in config["seeds"]}

filtered_pairs = [
    (d, s) for d, s in zip(DATASET_LIST.dataset, DATASET_LIST.seed)
    if d in allowed_datasets and (not allowed_seeds or s in allowed_seeds)
]

DATASET_LIST = type(DATASET_LIST)(
    dataset=[d for d, _ in filtered_pairs],
    seed=[s for _, s in filtered_pairs],
)
N_STATES = 7

rule all:
    input: os.path.join(eval_dir, "stats.csv"),# os.path.join(eval_dir, "analysis_notebook.ipynb"),

rule run_cellmates:
    input: os.path.join(data_dir, "{dataset}", "{seed}", "anndata.h5ad")
    output:
        cm_dist=os.path.join(data_dir, "{dataset}", "{seed}", "cm_out", "distance_matrix.npy"),
        cm_tree=os.path.join(data_dir, "{dataset}", "{seed}", "cm_out", "tree.nwk"),
        cm_cells=os.path.join(data_dir, "{dataset}", "{seed}", "cm_out", "cell_names.txt"),
        cm_diagnostics=os.path.join(data_dir, "{dataset}", "{seed}", "cm_out", "em_diagnostics.pkl")
    params:
        directory=os.path.join(data_dir, "{dataset}", "{seed}", "cm_out")
    conda: "cellmates"
    benchmark: os.path.join(data_dir, "{dataset}", "{seed}", "cm_out", "benchmark_run_cellmates.tsv")
    #threads: 16
    shell: """
    cellmates -i {input} -o {params.directory} -v 2 --n-states {N_STATES} --num-processors {threads} --tau 5 --learn-obs-params --save-diagnostics --numpy
    """

rule prepare_medicc2:
    input: os.path.join(data_dir, "{dataset}", "{seed}", "anndata.h5ad")
    output: os.path.join(data_dir, "{dataset}", "{seed}", "med_input.tsv")
    conda: "cellmates"
    shell: """
    python workflow/scripts/prepare_medicc2_input.py --input {input} --output {output} --layer-name noisy-cn
    """

rule prepare_dice:
    input: os.path.join(data_dir, "{dataset}", "{seed}", "anndata.h5ad")
    output: os.path.join(data_dir, "{dataset}", "{seed}", "dice_input.tsv")
    conda: "cellmates"
    shell: """
    python workflow/scripts/prepare_dice_input.py --input {input} --output {output} --layer-name noisy-cn
    """

rule run_medicc2:
    input: os.path.join(data_dir, "{dataset}", "{seed}", "med_input.tsv")
    output: os.path.join(data_dir, "{dataset}", "{seed}", "medicc2_out", "med_input_final_tree.nwk")
    benchmark: os.path.join(data_dir, "{dataset}", "{seed}", "benchmark_run_medicc2.tsv")
    conda: "medicc2"
    params:
        directory=os.path.join(data_dir, "{dataset}", "{seed}", "medicc2_out")
    shell: """
    medicc2 {input} {params.directory} -j {threads} --plot auto --no-wgd
    """

rule run_dice:
    input: os.path.join(data_dir, "{dataset}", "{seed}", "dice_input.tsv")
    output: os.path.join(data_dir, "{dataset}", "{seed}", "dice_out", "standard_root_balME_tree.nwk")
    benchmark: os.path.join(data_dir, "{dataset}", "{seed}", "benchmark_run_dice.tsv")
    conda: "dice"
    params:
        directory=os.path.join(data_dir, "{dataset}", "{seed}", "dice_out")
    shell: """
    dice -i {input} -o {params.directory} -m balME
    """

rule run_cellmates_cn:
    input: os.path.join(data_dir, "{dataset}", "{seed}", "anndata.h5ad")
    output:
        cm_dist=os.path.join(data_dir, "{dataset}", "{seed}", "cm_out_cn", "distance_matrix.npy"),
        cm_tree=os.path.join(data_dir, "{dataset}", "{seed}", "cm_out_cn", "tree.nwk"),
        cm_cells=os.path.join(data_dir, "{dataset}", "{seed}", "cm_out_cn", "cell_names.txt"),
        cm_diagnostics=os.path.join(data_dir, "{dataset}", "{seed}", "cm_out_cn", "em_diagnostics.pkl")
    params:
        directory=os.path.join(data_dir, "{dataset}", "{seed}", "cm_out_cn")
    conda: "cellmates"
    benchmark: os.path.join(data_dir, "{dataset}", "{seed}", "cm_out_cn", "benchmark_run_cellmates_cn.tsv")
    #threads: 16
    shell: """
    cellmates -i {input} -o {params.directory} -v 2 --n-states {N_STATES} --num-processors {threads} --save-diagnostics --use-copynumbers --numpy --layer-name noisy-cn
    """

rule evaluate:
    input:
        truth_ad=os.path.join(data_dir, "{dataset}", "{seed}", "anndata.h5ad"),
        cm_dist=os.path.join(data_dir, "{dataset}", "{seed}","cm_out{datatype}","distance_matrix.npy"),
        cm_tree=os.path.join(data_dir, "{dataset}", "{seed}","cm_out{datatype}","tree.nwk"),
        cm_cells=os.path.join(data_dir, "{dataset}", "{seed}","cm_out{datatype}","cell_names.txt"),
        medicc2_nwk=os.path.join(data_dir,"{dataset}","{seed}","medicc2_out","med_input_final_tree.nwk"),
        dice_nwk=os.path.join(data_dir,"{dataset}","{seed}","dice_out","standard_root_balME_tree.nwk")
    output: os.path.join(data_dir, "{dataset}", "{seed}","eval_tmp{datatype}.csv")
    params:
        n_states=N_STATES,
        dataset=lambda wc: wc.dataset,
        seed=lambda wc: int(wc.seed),
        method=lambda wc: "cn" if wc.datatype == "_cn" else "reads"
    conda: "cellmates"
    shell: """
    python workflow/scripts/evaluate_results.py \
            --adata-path {input.truth_ad} \
            --dist-path {input.cm_dist} \
            --tree-path {input.cm_tree} \
            --cells-path {input.cm_cells} \
            --out-path {output} \
            --n-states {params.n_states} \
            --dataset {params.dataset} \
            --seed {params.seed} \
            --datatype {params.method} \
            --medicc2-tree {input.medicc2_nwk} \
            --dice-tree {input.dice_nwk}
    """

rule combine_results:
    input: expand(os.path.join(data_dir, "{dataset}","{seed}","eval_tmp{datatype}.csv"), dataset=DATASET_LIST.dataset, seed=DATASET_LIST.seed, datatype=datatypes)
    output: os.path.join(eval_dir, "stats.csv")
    shell: """
    echo "Combining results"
    head -n 1 {input[0]} > {output}
    for f in {input}; do
        tail -n +2 $f >> {output}
    done
    """

rule analysis_notebook:
    input: os.path.join(eval_dir, "stats.csv")
    conda: "cellmates"
    log: os.path.join(eval_dir, "analysis_notebook.ipynb")
    notebook: "notebooks/plots.py.ipynb"

