#data_dir: "/home/vittorio.zampinetti/Cellmates/reproducibility/workflows/cnasim_makedata/results"
data_dir: "/proj/sc_ml/shared/cnasim_data/dice_benchmark_reboot"
datasets: ['A2_0', 'A2_1']
datatypes: ['', '_cn']
seeds: [0, 1, 2, 3, 4]  # Empty list indicates all seeds that are available
