n_cells: [10, 20, 50]
n_chrom: [2]
n_bins: [100, 500, 1000]
n_event_per_edge: [2, 5, 10]  #lambda param
n_clones: [2]
boundary_noise: [0.04]
jitter: [0.1]
n_replicates: 5
normal_fraction: 0.2
n_states: 7
