seeds: 10
noise_level: 0

defaults:
  n_cells: 250
  n_chromosomes: 22
  chromosome_length: 100
  mean_cnas_per_edge: 2
  bin_size: 1000000
  n_clones: 0
  wgd: false
  boundary_noise: 0
  jitter: 0

A:
  variable: n_cells
  values: [10, 25, 50, 75, 100, 250, 500]

B:
  variable: [n_chromosomes, chromosome_length]  # chrom length in Mbp
  values:
    - [1, 100]
    - [2, 100]
    - [5, 100]
    - [10, 100]
    - [15, 100]
    - [1, 50]
    - [1, 200]
    - [1, 500]
    - [1, 750]
    - [1, 1000]

C:
  variable: [wgd, n_clones, founder_chrom_rate, clone_chrom_rate, chrom_arm_rate]
  values:
    - [true, 0, 0, null, null]
    - [true, 0, 2, null, 0.75]
    - [false, 2, 2, 2, 0.75]
    - [false, 4, 2, 2, 0.75]
    - [false, 6, 2, 2, 0.75]
    - [false, 4, 0, 2, 0.75]
    - [false, 4, 2, 2, 0]
    - [true, 4, 2, 2, 0.75]

D:
  variable: mean_cnas_per_edge
  values: [0.5, 1, 2, 3, 4, 5, 7.5, 10]

E:
  variable: [bin_size, min_cn_length]
  values:
    - [1000000, 10000]
    - [1000000, 100000]
    - [500000, 1000]
    - [2000000, 1000]
    - [5000000, 1000]
    - [10000000, 1000]

F:
  variable: [boundary_noise, jitter]
  values:
    - [0.05, 0.02]
    - [0.15, 0.02]
    - [0.05, 0.04]
    - [0.15, 0.04]
    - [0.05, 0.06]
    - [0.15, 0.06]
    - [0.05, 0.08]
    - [0.15, 0.08]
    - [0.05, 0.10]
    - [0.15, 0.10]
    - [0.05, 0.12]
    - [0.15, 0.12]
