seeds: 10
noise_level: 0
results_dir: /proj/sc_ml/shared/cnasim_data/dice_benchmark_reboot

defaults:
  n_cells: 50
  n_chromosomes: 10
  chromosome_length: 100
  mean_cnas_per_edge: 2
  cn_length_mean: 5000000
  bin_size: 500000
  n_clones: 0
  wgd: false

levels_boundary_noise: [0, 0.04, 0.02]
levels_jitter: [0, 0.1, 0.1]

#Cs:
#  variable: [wgd, n_clones, founder_chrom_rate, clone_chrom_rate, chrom_arm_rate]
#  values:
#    - [false, 4, 2, 2, 0]
#    - [true, 4, 2, 2, 0.75]
#
Ds:
  variable: mean_cnas_per_edge # placement_param
  values: [2, 5, 10, 8]

Fs:
  variable: [boundary_noise, jitter, coverage, n_clones]  # error_rate_1, error_rate_2, coverage, num_clones
  values:
    - [0.05, 0.02, 0.2 , 0]
    - [0.15, 0.02, 0.2 , 0]
    - [0.05, 0.04, 0.1 , 0]
    - [0.15, 0.04, 0.1 , 0]
    - [0.05, 0.06, 0.08, 0]
    - [0.15, 0.06, 0.08, 0]
    - [0.05, 0.10, 0.05, 0]
    - [0.15, 0.10, 0.05, 0]
    - [0.05, 0.02, 0.2 , 4]
    - [0.05, 0.04, 0.1 , 4]
    - [0.05, 0.06, 0.08, 4]
    - [0.05, 0.10, 0.05, 4]

Gs:
  variable: [mean_cnas_per_edge, cn_length_mean, n_clones]  # placement_param, cn_length_mean, num_clones
  values:
    - [5, 10000000, 4]
    - [5, 20000000, 4]
    - [10, 10000000, 4]
    - [10, 20000000, 4]
    - [2, 10000000, 4]
    - [2, 20000000, 4]
