executor: slurm
jobs: 18
cores: 18

set-threads:
  run_cellmates: 1
  run_cellmates_cn: 1

#set-resources:
#  run_cellmates:
#    runtime: 100
#    mem_mb_per_cpu: 8000
#  run_cellmates_cn:
#    runtime: 100
#    mem_mb_per_cpu: 8000

default-resources:
  mem_mb_per_cpu: 8000
  runtime: 100  # 400' required for 25 cells
  slurm_account: "naiss2024-22-1623"

